version: "3"

services:
  innovator-api:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: "mysql"
    restart: always
    environment:
      MYSQL_USER: 'root'
      MYSQL_PASS: 'zsxadc1234'
    volumes:
      - /var/lib/mysql
    ports:
      - "3306:3306"