version: "3.3"

services:
#  db:
#    image: mysql:latest
#    container_name: mysql-db
#    environment:
#      - MYSQL_ROOT_PASSWORD=zsxadc1234
#    ports:
#      - "3306:3306"
#    restart: always
#    volumes:
#      - ./db:/var/lib/mysql
#
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin:latest
#    container_name: my-php-myadmin
#    ports:
#      - "8082:80"
#    restart: always
#    depends_on:
#      - db
#    environment:
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: zsxadc1234

  innovator-api:
    image: innovator-api
    container_name: innovator-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
#    depends_on:
#      - db
    volumes:
      - "/root/uploadFiles:/root/uploadFiles/"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/innovator?createDatabaseIfNotExist=true
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: zsxadc1234

#volumes:
#  -db: